name: fluttermoji
description: A light-weight and highly customizable SVG avatar library for
  Flutter apps. Provides a Customizer Widget, CircleAvatar and other utility
  functions that are ready-to-use.
version: 1.0.3
# author: Suraj Kumar
homepage: https://github.com/psk907/fluttermoji

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  get: ^4.6.5
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - attributeicons/
